Temporarily downgrade `rake`
The recent release broke several dependencies:

    rake aborted!
    NoMethodError: undefined method `last_comment' for #<Rake::Application:0x007f7f8314acd0>
    /Users/weppos/.rvm/gems/ruby-2.3.0@dnsimple-ruby/gems/yard-0.8.7.6/lib/yard/rake/yardoc_task.rb:69:in `define'
    /Users/weppos/.rvm/gems/ruby-2.3.0@dnsimple-ruby/gems/yard-0.8.7.6/lib/yard/rake/yardoc_task.rb:61:in `initialize'
    /Users/weppos/Code/dnsimple-ruby/Rakefile:16:in `new'
    /Users/weppos/Code/dnsimple-ruby/Rakefile:16:in `<top (required)>'
    /Users/weppos/.rvm/gems/ruby-2.3.0@dnsimple-ruby/bin/ruby_executable_hooks:15:in `eval'
    /Users/weppos/.rvm/gems/ruby-2.3.0@dnsimple-ruby/bin/ruby_executable_hooks:15:in `<main>'
    (See full trace by running task with --trace)