Don't try to update rubygems
This happens only for Ruby 2.2 and 2.3

```shell
$ gem update --system
ERROR:  Error installing rubygems-update:
	rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
Updating rubygems-update
The command "gem update --system" failed and exited with 1 during .
```